source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
target 'ICACrashReporter_Example' do
	pod 'ICACrashReporter/Crittercism', :path => '../../'
	pod 'ICACrashReporter/GoogleAnalytics', :path => '../../'
end
